manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: delock
      url-base: https://github.com/delock
  projects:
    - name: zmk
      remote: delock
      revision: main-3.2
      import: app/west.yml
  self:
    path: config
